/// Pronunciation drill sentences — everyday A2/B1 topics matching the exam's
/// theme circles. (Curated; extend freely or replace with course vocab.)
const drillSentences = <(String et, String en)>[
  ('Ma õpin eesti keelt.', 'I am learning Estonian.'),
  ('Kus on lähim bussipeatus?', 'Where is the nearest bus stop?'),
  ('Ma sooviksin ühe kohvi, palun.', 'I would like one coffee, please.'),
  ('Mis kell pood avatakse?', 'What time does the shop open?'),
  ('Ma elan Tallinnas juba kaks aastat.',
      'I have lived in Tallinn for two years already.'),
  ('Kas sa saaksid seda korrata?', 'Could you repeat that?'),
  ('Ilm on täna väga ilus.', 'The weather is very nice today.'),
  ('Ma töötan kontoris esmaspäevast reedeni.',
      'I work in an office from Monday to Friday.'),
  ('Mul on kaks last ja üks koer.', 'I have two children and one dog.'),
  ('Kui palju see maksab?', 'How much does it cost?'),
  ('Ma ei saa homme tulla, sest olen haige.',
      "I can't come tomorrow because I'm sick."),
  ('Palun rääkige natuke aeglasemalt.', 'Please speak a little more slowly.'),
  ('Mulle meeldib nädalavahetusel metsas jalutada.',
      'I like walking in the forest on weekends.'),
  ('Kas siin lähedal on mõni hea restoran?',
      'Is there a good restaurant nearby?'),
  ('Ma pean arsti juurde minema.', 'I need to go to the doctor.'),
  ('Buss number seitse sõidab kesklinna.',
      'Bus number seven goes to the city centre.'),
  ('Minu lemmiktoit on kartulisalat.', 'My favourite food is potato salad.'),
  ('Eile õhtul vaatasime sõpradega filmi.',
      'Last night we watched a film with friends.'),
  ('Suvel tahan mere ääres puhata.', 'In summer I want to rest by the sea.'),
  ('Vabandust, ma hilinesin natuke.', 'Sorry, I was a little late.'),
];
